### ISSUE TITLE
Syntax error near unexpected token `('

### ISSUE THREAD

**Issue by marvindanig** [capistrano-plugins/capistrano-delayed-job#2]
Hi Ruben,

When I do a

$ cap staging delayed_jobs:start 

it lets out the following error on console:

Running /usr/bin/env sudo service delayed_job_bubblin_staging start on bubbl.in
DEBUG[a02bb5f7] Command: ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.1.3 /usr/bin/env sudo service delayed_job_bubblin_staging start )
DEBUG[a02bb5f7] 	Invoking DelayedJob with command 'start'
DEBUG[a02bb5f7] 	-su: -c: line 0: syntax error near unexpected token `('
DEBUG[a02bb5f7] 	-su: -c: line 0: `cd /var/www/bubblin/current && HOME=/home/deployer RAILS_ENV=production nice -n 15 ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.1.3 ~/.rbenv/bin/rbenv exec bundle exec bin/delayed_job start -n 1 )'
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host bubbl.in: sudo exit status: 1
sudo stdout: Nothing written
sudo stderr: Nothing written
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/command.rb:97:in `exit_status='
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:148:in `block (5 levels) in _execute'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:551:in `call'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:551:in `do_request'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:561:in `channel_request'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:269:in `wait'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:170:in `block (3 levels) in _execute'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:514:in `call'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:514:in `do_open_confirmation'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:545:in `channel_open_confirmation'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:172:in `block (2 levels) in _execute'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:186:in `with_ssh'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:131:in `block in _execute'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:128:in `tap'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:128:in `_execute'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/capistrano-3.2.1/lib/capistrano/dsl.rb:27:in `sudo'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/capistrano-delayed-job-1.0.1/lib/capistrano/tasks/delayed_job.rake:39:in `block (4 levels) in <top (required)>'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/admin/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
SSHKit::Command::Failed: sudo exit status: 1

Any clues to what this is? Is it in someway related to the bash?

**Comment by rhomeister** [comment]
@marvindanig could you check if the latest version (which includes PR #3) fixes your problem? If so, please close this issue. Thanks go to @jcypret.

Sorry for the delay (no pun intended).
